# Generated by Django 2.2.4 on 2021-05-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_urlsummarization_url_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUploadMOdel',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('user_mail', models.EmailField(max_length=254)),
                ('document', models.FileField(default=False, upload_to='files/')),
            ],
        ),
    ]
