# Generated by Django 2.2.4 on 2021-05-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_documentsummarizationmodel_dno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDataExtractionModel',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('ino', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('data_extraction', models.TextField()),
                ('len_extracted_data', models.CharField(max_length=100)),
            ],
        ),
    ]
