# Generated by Django 2.2.4 on 2021-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_imagedataextractionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedataextractionmodel',
            name='user_mail',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
