# Generated by Django 2.2.4 on 2021-05-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_imagedataextractionmodel_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedataextractionmodel',
            name='content_keywords',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='imagedataextractionmodel',
            name='len_total_content',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
